import { CreatePropertyDto } from '../properties/dto/create-property.dto';
import {
  Currency,
  MarketingTag,
  Operation,
  PropertyType,
} from '../properties/enums/property.enums';

/**
 * A demo property: every `CreatePropertyDto` field except `neighborhoodId`,
 * which the CLI resolves from the barrio slug, plus the photo folder name
 * (inside the photos directory given to `seed`).
 */
export type DemoPropertyFixture = Omit<CreatePropertyDto, 'neighborhoodId'> & {
  neighborhood: string;
  photos: string;
};

export function toCreatePropertyDto(
  fixture: DemoPropertyFixture,
  neighborhoodId: string,
): CreatePropertyDto {
  const { neighborhood, photos, ...fields } = fixture;
  void neighborhood;
  void photos;
  return { ...fields, neighborhoodId };
}

const SERVICES = {
  hasWater: true,
  hasNaturalGas: true,
  hasSewer: true,
  hasElectricity: true,
  hasInternet: true,
};

export const DEMO_PROPERTIES: DemoPropertyFixture[] = [
  {
    operation: Operation.SALE,
    type: PropertyType.APARTMENT,
    title: 'Departamento 2 ambientes luminoso en Palermo',
    description:
      'Departamento de 2 ambientes en piso alto, con mucha luz natural y vista abierta. Living comedor amplio con salida al balcón, cocina independiente equipada y dormitorio con placard completo.\n\nEl edificio cuenta con amenities y portería, y está a pocas cuadras de plazas, cafés y transporte. Una zona muy buscada, ideal para vivir o como inversión.\n\nLas expensas son moderadas y la unidad se entrega en excelente estado de conservación. Coordiná tu visita.',
    neighborhood: 'palermo',
    address: 'Honduras 4800',
    showExactAddress: false,
    currency: Currency.USD,
    price: 135000,
    expenses: 180000,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    hasGarage: false,
    coveredArea: 42,
    totalArea: 46,
    age: 12,
    creditEligible: true,
    petsAllowed: true,
    immediateAvailability: true,
    marketingTag: MarketingTag.NONE,
    featured: false,
    ...SERVICES,
    photos: 'palermo-2amb',
  },
  {
    operation: Operation.SALE,
    type: PropertyType.APARTMENT,
    title: 'Departamento 3 ambientes en Belgrano con balcón',
    description:
      'Excelente 3 ambientes a metros de las barrancas de Belgrano. Living comedor con balcón corrido, dos dormitorios con placares y baño completo con ventilación natural.\n\nCocina separada con lavadero, pisos de parquet en perfecto estado y calefacción por radiadores. Cochera cubierta incluida en el precio.\n\nEdificio de categoría con seguridad las 24 horas y sala de usos múltiples. Una oportunidad difícil de repetir en la zona.',
    neighborhood: 'belgrano',
    address: 'Virrey del Pino 2400',
    showExactAddress: false,
    currency: Currency.USD,
    price: 210000,
    expenses: 260000,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    hasGarage: true,
    coveredArea: 68,
    totalArea: 74,
    age: 18,
    creditEligible: true,
    petsAllowed: true,
    immediateAvailability: false,
    marketingTag: MarketingTag.OPPORTUNITY,
    featured: true,
    ...SERVICES,
    photos: 'belgrano-3amb',
  },
  {
    operation: Operation.SALE,
    type: PropertyType.PH,
    title: 'PH reciclado a nuevo con patio en Villa Crespo',
    description:
      'PH al frente completamente reciclado, con patio propio y parrilla. Planta baja con living comedor integrado a la cocina, toilette y salida al patio; planta alta con dos dormitorios y baño completo.\n\nInstalaciones nuevas de agua, gas y electricidad, aberturas con doble vidrio y losa radiante. Sin expensas.\n\nEn pleno corazón de Villa Crespo, cerca de bares, comercios y subte B. Listo para mudarse.',
    neighborhood: 'villa-crespo',
    address: 'Thames 900',
    showExactAddress: false,
    currency: Currency.USD,
    price: 165000,
    expenses: 0,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    hasGarage: false,
    coveredArea: 78,
    totalArea: 95,
    age: 40,
    creditEligible: true,
    petsAllowed: true,
    immediateAvailability: true,
    marketingTag: MarketingTag.NEW,
    featured: true,
    ...SERVICES,
    photos: 'villa-crespo-ph',
  },
  {
    operation: Operation.SALE,
    type: PropertyType.HOUSE,
    title: 'Casa de 5 ambientes con jardín en Villa Devoto',
    description:
      'Casa en lote propio sobre una calle tranquila y arbolada de Villa Devoto. Planta baja con living, comedor, cocina comedor y toilette; jardín con quincho y pileta de lona.\n\nPlanta alta con tres dormitorios, dos baños y terraza. Garaje cubierto para dos autos y dependencia de servicio.\n\nA pocas cuadras de la plaza Arenales y del Tren San Martín. Ideal para familias que buscan espacio y tranquilidad dentro de la ciudad.',
    neighborhood: 'villa-devoto',
    address: 'Nueva York 4100',
    showExactAddress: false,
    currency: Currency.USD,
    price: 340000,
    expenses: 0,
    rooms: 5,
    bedrooms: 3,
    bathrooms: 3,
    hasGarage: true,
    coveredArea: 185,
    totalArea: 260,
    age: 35,
    creditEligible: false,
    petsAllowed: true,
    immediateAvailability: true,
    marketingTag: MarketingTag.NONE,
    featured: false,
    ...SERVICES,
    photos: 'villa-devoto-casa',
  },
  {
    operation: Operation.RENT,
    type: PropertyType.APARTMENT,
    title: 'Monoambiente moderno en Recoleta',
    description:
      'Monoambiente a estrenar en una de las zonas más cotizadas de la ciudad. Ambiente integrado con cocina equipada, placard completo y baño con ducha a ras de piso.\n\nEl edificio ofrece lavadero compartido, terraza con parrilla y portería. A metros de Av. Santa Fe, Av. Callao y el subte D.\n\nContrato por 3 años según la ley vigente. Se requiere garantía propietaria o seguro de caución.',
    neighborhood: 'recoleta',
    address: 'Junín 1500',
    showExactAddress: false,
    currency: Currency.ARS,
    price: 550000,
    expenses: 95000,
    rooms: 1,
    bedrooms: 0,
    bathrooms: 1,
    hasGarage: false,
    coveredArea: 28,
    totalArea: 30,
    age: 0,
    creditEligible: false,
    petsAllowed: false,
    immediateAvailability: true,
    marketingTag: MarketingTag.NONE,
    featured: false,
    ...SERVICES,
    photos: 'recoleta-mono',
  },
  {
    operation: Operation.RENT,
    type: PropertyType.APARTMENT,
    title: 'Departamento 2 ambientes en Caballito cerca del subte',
    description:
      'Departamento de 2 ambientes al contrafrente, silencioso y muy luminoso. Living comedor, cocina separada con bajo mesada, dormitorio amplio y baño completo.\n\nEdificio cuidado con ascensor, a dos cuadras del subte A y del Parque Rivadavia. Excelente conectividad y comercios en la zona.\n\nSe aceptan mascotas pequeñas. Disponible para mudarse en el mes.',
    neighborhood: 'caballito',
    address: 'Av. Rivadavia 5200',
    showExactAddress: false,
    currency: Currency.ARS,
    price: 650000,
    expenses: 120000,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    hasGarage: false,
    coveredArea: 45,
    totalArea: 48,
    age: 25,
    creditEligible: false,
    petsAllowed: true,
    immediateAvailability: true,
    marketingTag: MarketingTag.NONE,
    featured: true,
    ...SERVICES,
    photos: 'caballito-2amb',
  },
  {
    operation: Operation.RENT,
    type: PropertyType.APARTMENT,
    title: 'Departamento 3 ambientes con balcón en Núñez',
    description:
      'Departamento nuevo de 3 ambientes con balcón terraza y vista despejada. Living comedor integrado, cocina con muebles, dos dormitorios con placard y dos baños.\n\nEdificio con gimnasio, pileta, SUM y cochera opcional. A pasos del Parque Sarmiento y de la estación Núñez.\n\nUna propuesta moderna para quienes buscan comodidad y servicios en la zona norte de la ciudad.',
    neighborhood: 'nunez',
    address: 'Av. del Libertador 7800',
    showExactAddress: false,
    currency: Currency.ARS,
    price: 950000,
    expenses: 210000,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    hasGarage: true,
    coveredArea: 72,
    totalArea: 80,
    age: 1,
    creditEligible: false,
    petsAllowed: true,
    immediateAvailability: true,
    marketingTag: MarketingTag.NEW,
    featured: false,
    ...SERVICES,
    photos: 'nunez-3amb',
  },
  {
    operation: Operation.RENT,
    type: PropertyType.COMMERCIAL,
    title: 'Local comercial a la calle en Almagro',
    description:
      'Local a la calle sobre una avenida de gran circulación peatonal, con vidriera amplia y salón diáfano de planta libre. Baño y depósito en el fondo.\n\nHabilitación vigente para rubros comerciales generales. Persiana metálica de seguridad y conexión de gas y electricidad trifásica.\n\nA metros del subte B y de la estación Once, con excelente exposición para tu negocio.',
    neighborhood: 'almagro',
    address: 'Av. Corrientes 3900',
    showExactAddress: false,
    currency: Currency.ARS,
    price: 1200000,
    expenses: 85000,
    rooms: 1,
    bedrooms: 0,
    bathrooms: 1,
    hasGarage: false,
    coveredArea: 60,
    totalArea: 60,
    age: 30,
    creditEligible: false,
    petsAllowed: false,
    immediateAvailability: true,
    marketingTag: MarketingTag.NONE,
    featured: false,
    ...SERVICES,
    photos: 'almagro-local',
  },
];
